[manifest]
version = "1.0.0"
priority = 0

[[patches]]
[patches.pattern]
target = "main.lua"
pattern = "G:draw()"
position = "after"
payload = '''
Mng_DrawEverything()
'''
match_indent = true
times = 1